version: '3'
services:

  datasource:
    container_name: GG-datasource-bd
    image: gg/odb-source:v1
    volumes:
      - ./data/source_data/:/u01/app/oracle
    restart: unless-stopped
    build:
      context: . 
      dockerfile: Dockerfile-datasource
    networks:
      - ggbd_net

  gg-ora:
    container_name: GG-goldengateora-bd
    image: gg/ogg-goldengateora:v1
    volumes:
      - ./data/goldengate_ora/:/shared
    networks:
      - ggbd_net

  hbase:
    container_name: GG-hbase-bd
    image: gg/hbase_ogg:v2
    volumes:
      - ./data/hbase_ogg:/ogg
    ports:
      - 2181:2181
      - 60000:60000
      - 60010:60010
      - 60020:60020
      - 60030:60030
    build:
      context: .
      dockerfile: Dockerfile-hbase
    networks:
      - ggbd_net

networks:
  ggbd_net:
    driver: bridge
